version: '2'
services:
  varnish:
    build: ./varnish
    ports:
     - "8080:80"
    depends_on:
     - skill-query
     - skill-command
     - skill-ui
  skill-ui:
    build: ./skill-ui
    ports:
     - "8083:80"
  skill-command:
    build: ./skill-command
    ports:
     - "8081:8080"
    depends_on:
     - mongodb
     - rabbitmq
  skill-query:
    build: ./skill-query
    ports:
     - "8082:8080"
    depends_on:
     - elasticsearch
     - rabbitmq
  elasticsearch:
    image: elasticsearch:2.4.0
    container_name: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
  mongodb:
    image: mongo:3.4
    container_name: mongodb
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
