spring:
    application:
        exchange: employee.events.fanout.exchange
        queue: employee.default.queue
        databaseName: employees
        eventsCollectionName: events
        snapshotCollectionName: snapshots
    rabbitmq:
        hostname: rabbitmq
        username: test
        password: password
    data:
        mongodb:
            uri: mongodb://mongodb:27017/employees
